import "server-only";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { DraftFile, PublishedPromises } from "@/lib/promises";

// Review happens locally: drafts and published promises are JSON files in the repo, and
// publishing means committing src/data/promises.json.
export const reviewEnabled = process.env.NODE_ENV === "development";

const PENDING_DIR = join(process.cwd(), "data/promises/pending");
const PUBLISHED = join(process.cwd(), "src/data/promises.json");

const pendingFile = (officialId: string) => {
  // Official IDs are generated by us, but never let one escape the pending directory.
  if (!/^[\w-]+$/.test(officialId)) throw new Error("Bad official id");
  return join(PENDING_DIR, `${officialId}.json`);
};

export function listDraftFiles(): DraftFile[] {
  if (!existsSync(PENDING_DIR)) return [];
  return readdirSync(PENDING_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(join(PENDING_DIR, f), "utf8")) as DraftFile)
    .filter((f) => f.drafts.length);
}

export function readDraftFile(officialId: string): DraftFile | null {
  const path = pendingFile(officialId);
  return existsSync(path) ? (JSON.parse(readFileSync(path, "utf8")) as DraftFile) : null;
}

export function writeDraftFile(file: DraftFile) {
  writeFileSync(pendingFile(file.officialId), `${JSON.stringify(file, null, 2)}\n`);
}

export function readPublished(): Record<string, PublishedPromises> {
  return JSON.parse(readFileSync(PUBLISHED, "utf8"));
}

export function writePublished(data: Record<string, PublishedPromises>) {
  writeFileSync(PUBLISHED, `${JSON.stringify(data, null, 2)}\n`);
}
